# -*- coding: utf-8 -*-
"""config.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17y5Qh-u4x_kyAIkIfPv9P8SxTAKt5_u2
"""

RANDOM_STATE = 42
TEST_SIZE = 0.2
TARGET = "target"