# -*- coding: utf-8 -*-
"""temp.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17y5Qh-u4x_kyAIkIfPv9P8SxTAKt5_u2
"""

from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.svm import SVC


def build_model(C=1.0, kernel="rbf", gamma="scale"):
    """
    Build SVM pipeline (production-ready)
    """
    model = Pipeline([
        ("scaler", StandardScaler()),
        ("svm", SVC(C=C, kernel=kernel, gamma=gamma))
    ])

    return model


def train_model(model, X_train, y_train):
    """
    Train the model
    """
    model.fit(X_train, y_train)
    return model


def predict(model, X_test):
    """
    Generate predictions
    """
    return model.predict(X_test)