# -*- coding: utf-8 -*-
"""temp.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17y5Qh-u4x_kyAIkIfPv9P8SxTAKt5_u2
"""

import optuna

from sklearn.model_selection import cross_val_score
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.svm import SVC


def tune_svm(X_train, y_train, n_trials=50):

    def objective(trial):

        params = {
            "C": trial.suggest_float(
                "C",
                1e-3,
                100,
                log=True
            ),
            "kernel": trial.suggest_categorical(
                "kernel",
                ["linear", "rbf"]
            ),
            "gamma": trial.suggest_categorical(
                "gamma",
                ["scale", "auto"]
            )
        }

        pipeline = Pipeline([
            ("scaler", StandardScaler()),
            ("svm", SVC(**params))
        ])

        score = cross_val_score(
            estimator=pipeline,
            X=X_train,
            y=y_train,
            cv=5,
            scoring="f1",
            n_jobs=-1
        ).mean()

        return score

    study = optuna.create_study(direction="maximize")

    study.optimize(
        objective,
        n_trials=n_trials,
        show_progress_bar=True
    )

    return study.best_params